services:
    laravel.alpine:
        hostname: laravel.alpine
        build:
            context: ./docker/8.3-alpine
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/app'
        cap_add:
            - NET_ADMIN
        networks:
            sail:
                ipv4_address: 13.13.13.2
        depends_on:
            - laravel.pgsql
            - laravel.redis
    laravel.pgsql:
        hostname: laravel.pgsql
        image: 'postgres:17'
        ports:
            - '${DB_FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - './docker/pgsql/data:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
            - './docker/pgsql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf'
        networks:
            sail:
                ipv4_address: 13.13.13.3
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    laravel.redis:
        hostname: laravel.redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './docker/redis/data:/data'
        networks:
            sail:
                ipv4_address: 13.13.13.4
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
        ipam:
            config:
                -   subnet: 13.13.13.0/24
